CREATE USER chat IDENTIFIED BY chat;

dar privilegios

GRANT CREATE TABLE TO chat; 
GRANT CREATE VIEW TO chat; 
GRANT CREATE SEQUENCE TO chat; 
GRANT CREATE PROCEDURE TO chat; 
GRANT CREATE SYNONYM TO chat; 
GRANT UNLIMITED TABLESPACE TO chat; 
GRANT CREATE SESSION TO chat; 
GRANT CREATE TRIGGER TO chat; 
GRANT CREATE SEQUENCE TO chat; 
GRANT CREATE TABLE TO chat; 
GRANT UNLIMITED TABLESPACE TO chat; 
GRANT CONNECT, RESOURCE TO chat; 
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE TRIGGER TO chat; 
GRANT EXECUTE ON UTL_MAIL TO chat; 
GRANT EXECUTE ON UTL_SMTP TO chat; 
GRANT SELECT ON DBA_NETWORK_ACLS TO chat; 
GRANT EXECUTE ON UTL_MAIL TO chat; 
GRANT EXECUTE ON DBMS_ALERT TO chat;
