CREATE USER C##senati2 IDENTIFIED BY C##senati2;


GRANT CREATE TABLE TO C##senati2; 
GRANT CREATE VIEW TO C##senati2; 
GRANT CREATE SEQUENCE TO C##senati2; 
GRANT CREATE PROCEDURE TO C##senati2; 
GRANT CREATE SYNONYM TO C##senati2; 
GRANT UNLIMITED TABLESPACE TO C##senati2; 
GRANT CREATE SESSION TO C##senati2; 
GRANT CREATE TRIGGER TO C##senati2; 
GRANT CREATE SEQUENCE TO C##senati2; 
GRANT CREATE TABLE TO C##senati2; 
GRANT UNLIMITED TABLESPACE TO C##senati2; 
GRANT CONNECT, RESOURCE TO C##senati2; 
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE TRIGGER TO C##senati2; 
GRANT EXECUTE ON UTL_MAIL TO C##senati2; 
GRANT EXECUTE ON UTL_SMTP TO C##senati2; 
GRANT SELECT ON DBA_NETWORK_ACLS TO C##senati2; 
GRANT EXECUTE ON UTL_MAIL TO C##senati2; 
GRANT EXECUTE ON DBMS_ALERT TO C##senati2;



GRANT CONNECT, RESOURCE TO C##senati2;
