ALTER SESSION SET CONTAINER = XEPDB1;
Crear un nuevo usuario en oracle

CREATE USER ONOTIFICACIONES IDENTIFIED BY ONOTIFICACIONES;

dar privilegios

GRANT CREATE TABLE TO ONOTIFICACIONES; 
GRANT CREATE VIEW TO ONOTIFICACIONES; 
GRANT CREATE SEQUENCE TO ONOTIFICACIONES; 
GRANT CREATE PROCEDURE TO ONOTIFICACIONES; 
GRANT CREATE SYNONYM TO ONOTIFICACIONES; 
GRANT UNLIMITED TABLESPACE TO ONOTIFICACIONES; 
GRANT CREATE SESSION TO ONOTIFICACIONES; 
GRANT CREATE TRIGGER TO ONOTIFICACIONES; 
GRANT CREATE SEQUENCE TO ONOTIFICACIONES; 
GRANT CREATE TABLE TO ONOTIFICACIONES; 
GRANT UNLIMITED TABLESPACE TO ONOTIFICACIONES; 
GRANT CONNECT, RESOURCE TO ONOTIFICACIONES; 
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE TRIGGER TO ONOTIFICACIONES; 
GRANT EXECUTE ON UTL_MAIL TO ONOTIFICACIONES; 
GRANT EXECUTE ON UTL_SMTP TO ONOTIFICACIONES; 
GRANT SELECT ON DBA_NETWORK_ACLS TO ONOTIFICACIONES; 
GRANT EXECUTE ON UTL_MAIL TO ONOTIFICACIONES; 
GRANT EXECUTE ON DBMS_ALERT TO ONOTIFICACIONES;



CREATE TABLE CURSO_SEMESTRE (
    ID_CURSO NUMBER,
    ID_SEMESTRE NUMBER,
    CONSTRAINT PK_CURSO_SESION PRIMARY KEY (ID_CURSO, ID_SEMESTRE),
    CONSTRAINT FK_CURSO_SESION_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO),
    CONSTRAINT FK_CURSO_SESION_SEMESTRE FOREIGN KEY (ID_SEMESTRE) SEMESTRE SESIONES(ID_SEMESTRE)
);


CREATE TABLE SESION_UBICACION (
    ID_SESION NUMBER,
    ID_UBICACION NUMBER,
    CONSTRAINT PK_CURSO_UBICACION PRIMARY KEY (ID_SESION, ID_UBICACION),
    CONSTRAINT FK_CURSO_UBICACION_SESION FOREIGN KEY (ID_SESION) REFERENCES SESIONES(ID_SESION),
    CONSTRAINT FK_CURSO_UBICACION_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION),
);

CREATE TABLE EVALUACION_UBICACION (
    ID_EVALUACION NUMBER,
    ID_UBICACION NUMBER,
    CONSTRAINT PK_CURSO_UBICACION PRIMARY KEY (ID_EVALUACION, ID_UBICACION),
    CONSTRAINT FK_CURSO_UBICACION_EVALUACION FOREIGN KEY (ID_EVALUACION) REFERENCES EVALUACIONES(ID_EVALUACION),
    CONSTRAINT FK_CURSO_UBICACION_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION)
);

-- Crear tabla UBICACION
CREATE TABLE UBICACION (
    ID_UBICACION INTEGER PRIMARY KEY,
    T_NOMBRE VARCHAR2(100) NOT NULL,
    D_DESCRIPCION VARCHAR2(255)
);

-- Crear tabla SEMESTRE
CREATE TABLE SEMESTRE (
    ID_SEMESTRE INTEGER PRIMARY KEY,
    T_NOMBRE VARCHAR2(50) NOT NULL,
    D_FECHA_INICIO DATE NOT NULL,
    D_FECHA_FIN DATE NOT NULL
);
